name: aa_frame
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
# Networking
  http: ^1.1.0
# State Management
  provider: ^6.1.1
# Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.4
# Localization
  easy_localization: ^3.0.3
# Notifications
  flutter_local_notifications: ^18.0.1
# Image Caching
  cached_network_image: ^3.4.1
# Firebase
  firebase_core: ^3.12.1
  firebase_crashlytics: ^4.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
