name: aa_frame
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
# Networking
  http: ^1.1.0
# State Management
  provider: ^6.1.1
# Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.4
# Localization
  easy_localization: ^3.0.3
  intl: ^0.19.0
# File System
  path: ^1.9.0
  path_provider: ^2.1.2
# Notifications
  flutter_local_notifications: ^18.0.1
# UI Effects
  shimmer: ^3.0.0
# Image Caching
  cached_network_image: ^3.4.1
# Firebase
  firebase_core: ^3.12.1
  firebase_crashlytics: ^4.3.4
# SVG
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/svg/
