name: aa_frame
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
# Networking
  http: ^1.1.0
# State Management
  provider: ^6.1.1
# Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.4
# Localization
  easy_localization: ^3.0.3
  intl: ^0.19.0
# File System
  path: ^1.9.0
  path_provider: ^2.1.2
# Notifications
  flutter_local_notifications: ^18.0.1
# UI Effects
  shimmer: ^3.0.0
# Image Caching
  cached_network_image: ^3.4.1
# Firebase
  firebase_core: ^3.12.1
  firebase_crashlytics: ^4.3.4
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^6.1.4
# SVG
  flutter_svg: ^2.0.17
# JSON
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.11
  json_serializable: ^6.9.4
  freezed: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/svg/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash/splash.png
  branding: assets/splash/branding.png
  color_dark: "#121212"
  image_dark: assets/splash/splash.png
  branding_dark: assets/splash/branding_dark.png

  android_12:
    color: "#FFFFFF"
    image: assets/splash/splash_android12.png
    color_dark: "#121212"
    image_dark: assets/splash/splash_android12.png

  web: false
